# REF: https://github.com/rust-lang/rustfmt/blob/main/Configurations.md
array_width = 60
attr_fn_like_width = 70
binop_separator = "Front" # Front|Back
blank_lines_lower_bound = 1
black_lines_upper_bound = 1
brace_style = "SameLineWhere" # AlwaysNextLine|PreferSameLine|SameLineWhere
chain_width = 60
color = "Auto" # Auto|Always|Never
combine_control_expr = false
comment_width = 80
condense_wildcard_suffixes = true
control_brace_style = "AlwaysSameLine" # AlwaysNextLine|AlwaysSameLine|ClosingNextLine
disable_all_formatting = false # hell no
edition = "2024" # 2015|2018|2021|2024
empty_item_single_line = true
enum_discrim_align_threshold = 20
error_on_line_overflow = false
error_on_unformatted = true
fn_call_width = 60
fn_params_layout = "Tall" # Compressed|Tall|Vertical
fn_single_line = true
force_explicit_abi = true
force_multiline_blocks = false
format_code_in_doc_comments = true
doc_comment_code_block_width = 100
format_generated_files = true
generated_marker_line_search_limit = 5
format_macro_matches = true
format_macro_bodies = true
skip_macro_invocations = []
format_strings = true
hard_tabs = false # fuck tabs
hex_literal_case = "Lower" # Preserve|Upper|Lower
float_literal_trailing_zero = "Never" # Preserve|Always|IfNoPostfix|Never
show_parse_errors = true
# ignore = [] # same format as .gitignore
imports_indent = "Block" # Block|Visual
imports_layout = "HorizontalVertical" # Horizontal|Vertical|HorizontalVertical|Mixed
indent_style = "Block" # Block|Visual
inline_attribute_width = 0
match_arm_blocks = true
match_arm_leading_pipes = "Never" # Preserve|Always|Never
match_arm_indent = true
match_block_trailing_comma = true
max_width = 100
merge_derives = true
imports_granularity = "One" # Preserve|Crate|Module|Item|One
newline_style = "Unix" # Auto|Native|Unix|Windows
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
remove_nested_parens = true
reorder_impl_items = true
reorder_imports = true
group_imports = "StdExternalCrate" # Preserve|StdExternalCrate|One
reorder_modules = true
required_version = "1.8.0" # rustfmt version
short_array_element_width_threshold = 10
skip_children = false
single_line_if_else_max_width = 50
single_line_let_else_max_width = 50
space_after_colon = true
space_before_colon = false
spaces_around_ranges = false
struct_field_align_threshold = 20
struct_lit_single_line = true
struct_lit_width = 18
struct_variant_width = 35
style_edition = "2024" # 2015|2018|2021|2024(unstable variant)
tab_spaces = 4
trailing_comma = "Always" # Vertical|Always|Never
trailing_semicolon = true
type_punctuation_density = "Wide" # Compressed|Wide
unstable_features = true
use_field_init_shorthand = true
use_small_heuristics = "Default" # Default|Off|Max
use_try_shorthand = true
where_single_line = false
wrap_comments = true
